# Generated by Django 5.0 on 2024-04-15 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preventa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleIngenieria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('alcance', models.CharField(max_length=500)),
                ('entrergables', models.CharField(max_length=500)),
                ('info_requerida_mandante', models.CharField(max_length=500)),
                ('limitaciones', models.CharField(max_length=500)),
                ('exclusiones', models.CharField(max_length=500)),
                ('plazo_entrega', models.CharField(max_length=200)),
                ('costo', models.IntegerField()),
                ('firma', models.CharField(max_length=100)),
                ('subtotal_item', models.IntegerField()),
                ('subtotal_item_neto', models.IntegerField()),
                ('total_item_neto', models.IntegerField()),
                ('id_preventa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preventa.preventa')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preventa.usuario')),
            ],
        ),
    ]
