# Generated by Django 5.0 on 2024-04-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preventa', '0002_detalleingenieria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preventa',
            old_name='cliente',
            new_name='nombre_cliente',
        ),
        migrations.RenameField(
            model_name='preventa',
            old_name='nombre',
            new_name='nombre_proyecto',
        ),
        migrations.RenameField(
            model_name='preventa',
            old_name='solicitante',
            new_name='nombre_solicitante',
        ),
        migrations.RemoveField(
            model_name='detalleingenieria',
            name='entrergables',
        ),
        migrations.AddField(
            model_name='detalleingenieria',
            name='entregables',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='detalleingenieria',
            name='total_hh',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detalleingenieria',
            name='alcance',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='detalleingenieria',
            name='exclusiones',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='detalleingenieria',
            name='info_requerida_mandante',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='detalleingenieria',
            name='limitaciones',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='detalleingenieria',
            name='plazo_entrega',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='preventa',
            name='correlativo',
            field=models.IntegerField(),
        ),
    ]
