# Generated by Django 5.0 on 2024-04-18 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preventa', '0007_preventa_nombre_vertical'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preventa',
            name='nombre_vertical',
            field=models.CharField(choices=[('estandar', 'Estandar'), ('zona_norte_antofagasta', 'Zona Norte Antofagasta'), ('data_center', 'Data Center'), ('mineria_y_utilities', 'Mineria y Utilities'), ('industrias', 'Industrias'), ('telecomunicaciones', 'Telecomunicaciones'), ('transporte_y_gobierno', 'Transporte y Gobierno')], max_length=50),
        ),
    ]
