# Generated by Django 5.0 on 2024-04-18 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preventa', '0008_alter_preventa_nombre_vertical'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_item', models.CharField(max_length=100)),
                ('detalle_item', models.CharField(max_length=100, null=True)),
                ('valor_unitario', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.AlterField(
            model_name='detalleingenieria',
            name='alcance',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detalleingenieria',
            name='entregables',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detalleingenieria',
            name='exclusiones',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detalleingenieria',
            name='info_requerida_mandante',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detalleingenieria',
            name='limitaciones',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detalleingenieria',
            name='plazo_entrega',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
