# Generated by Django 5.0 on 2024-04-18 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preventa', '0009_item_delete_usuario_alter_detalleingenieria_alcance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alcance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_alcance', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HorasHombre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('pm', 'Project Manager'), ('ie', 'Ingeniero Especialista'), ('dp', 'Dibujante Proyectista'), ('cd', 'Control Documentos'), ('sp', 'Supervisor de Proyecto'), ('it', 'Ingeniero de Terreno'), ('mc', 'Medicion Certificada')], max_length=50)),
                ('valor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('costo_total', models.IntegerField()),
                ('precio_total', models.IntegerField()),
                ('id_detalle_ingenieria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preventa.detalleingenieria')),
                ('id_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preventa.item')),
            ],
        ),
        migrations.CreateModel(
            name='SubAlcance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_subalcance', models.CharField(max_length=100)),
                ('id_alcance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preventa.alcance')),
            ],
        ),
        migrations.CreateModel(
            name='HHDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('subtotal', models.IntegerField()),
                ('total', models.IntegerField()),
                ('id_detalle_ingenieria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preventa.detalleingenieria')),
                ('id_hh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preventa.horashombre')),
                ('id_subalcance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preventa.subalcance')),
            ],
        ),
    ]
